# Generated by Django 4.1.7 on 2023-05-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfirst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='country',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
